# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wsm2_FM1SlrqBAGczNrVM_2gIcJPFe7X
"""

!pip install streamlit
import streamlit as st
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import OLSInfluence

# Configuración inicial del layout
st.set_page_config(page_title="IA Avanzada: Laboratorio de Diagnóstico de Datos", layout="wide")

st.title("🎯 Competencia: Sabotaje del Gradiente & Auditoría de Datos Avanzada")
st.markdown("""
Esta herramienta evalúa cómo los puntos de **Apalancamiento (Leverage)**, **Residuos**, **DFFITS** y **DFBETAS** afectan el entrenamiento de un modelo lineal.
- **Equipo Atacante:** Inyecta datos ocultos para alterar los parámetros.
- **Equipo Auditor:** Usa métricas de diagnóstico avanzado para identificar los puntos saboteadores.
""")

# Sidebar
st.sidebar.header("🕹️ Panel de Control")

# -----------------------------------------------------------------------------
# CONTROL DE GENERACIÓN ALEATORIA DEL DATASET BASE
# -----------------------------------------------------------------------------
st.sidebar.subheader("🎲 Configuración del Dataset Aleatorio")

# Botón para regenerar semilla
if 'semilla_base' not in st.session_state:
    st.session_state['semilla_base'] = 42

if st.sidebar.button("🔄 Generar Nuevo Dataset Aleatorio"):
    st.session_state['semilla_base'] = np.random.randint(1, 10000)

n_muestras = st.sidebar.slider("Número de muestras ($N$):", min_value=20, max_value=60, value=30, step=5)
ruido = st.sidebar.slider("Nivel de ruido ($σ$):", min_value=1.0, max_value=15.0, value=5.0, step=0.5)

# Función de generación con semilla dinámica
def generar_datos_base(seed, n, sigma):
    np.random.seed(seed)
    # Generar X e Y aleatorios con cierta estructura lineal + ruido aleatorio
    x_min, x_max = np.random.uniform(5, 15), np.random.uniform(45, 60)
    X = np.random.uniform(x_min, x_max, size=n)
    w_real = np.random.uniform(1.5, 3.5)
    b_real = np.random.uniform(5.0, 25.0)
    y = w_real * X + b_real + np.random.normal(0, sigma, size=n)
    df = pd.DataFrame({'X': X, 'Y': y, 'Tipo': 'Base'})
    # Desordenar explícitamente las filas
    df = df.sample(frac=1, random_state=seed).reset_index(drop=True)
    return df

df_base = generar_datos_base(st.session_state['semilla_base'], n_muestras, ruido)

modo = st.sidebar.radio("Selecciona la Fase:", ["1. Dataset Base", "2. Fase de Ataque (Sabotaje)", "3. Fase de Auditoría (Defensa)"])

# -----------------------------------------------------------------------------
# FASE 1: DATASET BASE
# -----------------------------------------------------------------------------
if modo == "1. Dataset Base":
    st.subheader("📌 Estado Inicial del Modelo (Línea Base Aleatoria)")
    col1, col2 = st.columns([1, 2])
    X_design = sm.add_constant(df_base['X'])
    model_base = sm.OLS(df_base['Y'], X_design).fit()
    with col1:
        st.write("### Parámetros Generados")
        st.metric("Pendiente Base (w)", f"{model_base.params['X']:.3f}")
        st.metric("Intercepto Base (b)", f"{model_base.params['const']:.3f}")
        st.metric("R² Score", f"{model_base.rsquared:.3f}")
        st.caption(f"Semilla actual: `{st.session_state['semilla_base']}`. Puedes cambiarla desde la barra lateral.")
    with col2:
        fig, ax = plt.subplots(figsize=(8, 5))
        ax.scatter(df_base['X'], df_base['Y'], color='blue', label='Datos Base Aleatorios', s=50)
        for i, txt in enumerate(df_base.index):
            ax.annotate(txt, (df_base['X'].iloc[i]+0.4, df_base['Y'].iloc[i]), fontsize=8, alpha=0.6)
        x_vals = np.linspace(df_base['X'].min()-5, df_base['X'].max()+5, 100)
        y_vals = model_base.params['const'] + model_base.params['X'] * x_vals
        ax.plot(x_vals, y_vals, color='black', linestyle='--', label='Regresión Base ($L_0$)​')
        ax.set_xlabel("Variable X")
        ax.set_ylabel("Variable Y")
        ax.legend()
        ax.grid(True, linestyle=':', alpha=0.6)
        st.pyplot(fig)

# -----------------------------------------------------------------------------
# FASE 2: ATAQUE (SABOTAJE)
# -----------------------------------------------------------------------------
elif modo == "2. Fase de Ataque (Sabotaje)":
    st.subheader("🔴 Fase de Ataque: Introduce Puntos Saboteadores")
    st.warning("⚠️ Equipo Auditor: ¡No miren la pantalla durante esta fase!")
    col1, col2 = st.columns([1, 2])
    with col1:
        st.write("### Agregar Puntos de Ataque")
        num_puntos = st.radio("Número de puntos a inyectar:", [1, 2])
        seed_sabotaje = st.number_input("Semilla de mezcla aleatoria:", value=123, step=1)
        # Calcular límites dinámicos según el dataset generado
        x_min_val, x_max_val = float(df_base['X'].min() - 10), float(df_base['X'].max() + 10)
        y_min_val, y_max_val = float(df_base['Y'].min() - 20), float(df_base['Y'].max() + 30)
        puntos_ataque = []
        for i in range(num_puntos):
            st.markdown(f"**Punto Saboteador #{i+1}**")
            px = st.slider(f"X_{i+1}", min_value=x_min_val, max_value=x_max_val, value=(x_min_val+x_max_val)/2 if i==0 else x_max_val, key=f"x_{i}")
            py = st.slider(f"Y_{i+1}", min_value=y_min_val, max_value=y_max_val, value=y_max_val if i==0 else y_min_val, key=f"y_{i}")
            puntos_ataque.append({'X': px, 'Y': py, 'Tipo': 'Saboteador'})
        df_temporal = pd.concat([df_base, pd.DataFrame(puntos_ataque)], ignore_index=True)
        df_ataque = df_temporal.sample(frac=1, random_state=seed_sabotaje).reset_index(drop=True)
        st.session_state['df_modificado'] = df_ataque
        # Recalcular Modelo y Métricas Diagnósticas
        X_att = sm.add_constant(df_ataque['X'])
        model_att = sm.OLS(df_ataque['Y'], X_att).fit()
        influence_att = OLSInfluence(model_att)
        leverage_att = influence_att.hat_matrix_diag
        stud_residuals_att = influence_att.resid_studentized_internal
        cooks_d_att, _ = influence_att.cooks_distance
        (dffits_att, _) = influence_att.dffits
        dfbetas_att = influence_att.dfbetas
        X_base_design = sm.add_constant(df_base['X'])
        model_base = sm.OLS(df_base['Y'], X_base_design).fit()
        st.write("---")
        st.write("### Impacto General en el Modelo")
        delta_w = model_att.params['X'] - model_base.params['X']
        st.metric("Nueva Pendiente (w)", f"{model_att.params['X']:.3f}", delta=f"{delta_w:.3f}")
        st.metric("Nuevo R²", f"{model_att.rsquared:.3f}", delta=f"{model_att.rsquared - model_base.rsquared:.3f}")

    with col2:
        fig, ax = plt.subplots(figsize=(8, 4.5))
        df_base_only = df_ataque[df_ataque['Tipo'] == 'Base']
        df_sab_only = df_ataque[df_ataque['Tipo'] == 'Saboteador']
        ax.scatter(df_base_only['X'], df_base_only['Y'], color='blue', label='Datos Base', s=50, alpha=0.6)
        ax.scatter(df_sab_only['X'], df_sab_only['Y'], color='red', label='Puntos Saboteadores', s=120, marker='X')
        for i, txt in enumerate(df_ataque.index):
            color_txt = 'red' if df_ataque.iloc[i]['Tipo'] == 'Saboteador' else 'black'
            ax.annotate(f"i={txt}", (df_ataque['X'].iloc[i]+0.4, df_ataque['Y'].iloc[i]), fontsize=8, color=color_txt, weight='bold')
        x_vals = np.linspace(df_ataque['X'].min()-5, df_ataque['X'].max()+5, 100)
        y_base_vals = model_base.params['const'] + model_base.params['X'] * x_vals
        y_att_vals = model_att.params['const'] + model_att.params['X'] * x_vals
        ax.plot(x_vals, y_base_vals, color='black', linestyle='--', label='Regresión Original (L_0)​')
        ax.plot(x_vals, y_att_vals, color='red', linewidth=2, label='Nueva Regresión (L_alterada)')
        ax.set_xlabel("Variable X")
        ax.set_ylabel("Variable Y")
        ax.legend()
        ax.grid(True, linestyle=':', alpha=0.6)
        fig.tight_layout()
        st.pyplot(fig)
    st.write("---")
    # ---------------------------------------------------------------------
    # TABLA DE DIAGNÓSTICO EN TIEMPO REAL PARA EL ATACANTE
    # ---------------------------------------------------------------------
    st.subheader("📊 Diagnóstico de tus Puntos Saboteadores")
    st.caption("Usa estos datos para evaluar si tus puntos destacan demasiado en las métricas de la defensa.")
    indices_saboteadores = list(df_sab_only.index)
    n_total = len(df_ataque)
    p_param = 2
    df_sab_metricas = pd.DataFrame({
        'Index': indices_saboteadores,
        'X': df_sab_only['X'].values.round(2),
        'Y': df_sab_only['Y'].values.round(2),
        'Leverage (hii)': np.round(leverage_att[indices_saboteadores], 3),
        'Residuo Stud (r_i)': np.round(stud_residuals_att[indices_saboteadores], 3),
        'Cook D': np.round(cooks_d_att[indices_saboteadores], 3),
        'DFFITS': np.round(dffits_att[indices_saboteadores], 3),
        'DFBETA (w)': np.round(dfbetas_att[indices_saboteadores, 1], 3)
    }).set_index('Index')
    st.dataframe(df_sab_metricas.style.highlight_max(axis=0, color='lightcoral'))
    # Resumen de alertas para el atacante
    umb_cook = 4 / n_total
    umb_lev = 2 * (p_param / n_total)
    alertas = []
    for idx in indices_saboteadores:
        if cooks_d_att[idx] > umb_cook:
            alertas.append(f"⚠️ El punto `i={idx}` supera el umbral de Cook ({cooks_d_att[idx]:.3f} > {umb_cook:.3f}). ¡Será fácil de detectar!")
        if leverage_att[idx] > umb_lev:
            alertas.append(f"📢 El punto `i={idx}` tiene un apalancamiento alto ({leverage_att[idx]:.3f} > {umb_lev:.3f}).")
    if alertas:
        for al in alertas:
            st.warning(al)
    else:
        st.success("✨ ¡Buen trabajo de camuflaje! Ningún punto saboteador supera fuertemente la prueba de Cook.")

# -----------------------------------------------------------------------------
# FASE 3: AUDITORÍA Y DETECCIÓN (DEFENSA)
# -----------------------------------------------------------------------------
else:
    st.subheader("🔵 Fase de Auditoría: Identificación de Puntos Influyentes")
    if 'df_modificado' not in st.session_state:
        st.error("❌ Aón no se han inyectado puntos en la 'Fase de Ataque'.")
    else:
        df_auditoria = st.session_state['df_modificado']
        # Cálculos de Diagnóstico
        X_aud = sm.add_constant(df_auditoria['X'])
        model_aud = sm.OLS(df_auditoria['Y'], X_aud).fit()
        influence = OLSInfluence(model_aud)
        leverage = influence.hat_matrix_diag
        stud_residuals = influence.resid_studentized_internal
        cooks_d, _ = influence.cooks_distance
        (dffits, _) = influence.dffits
        dfbetas = influence.dfbetas
        n = len(df_auditoria)
        p = 2
        # Umbrales teóricos
        umbral_cook = 4 / n
        umbral_leverage = 2 * (p / n)
        umbral_dffits = 2 * np.sqrt(p / n)
        umbral_dfbetas = 2 / np.sqrt(n)
        st.write("Analiza los diagnósticos métricos para identificar los índices saboteadores:")
        # Crear la figura y subplots
        fig, axes = plt.subplots(2, 2, figsize=(16, 10))
        # 1. Leverage (Sin símbolos de LaTeX)
        axes[0, 0].stem(range(n), leverage, markerfmt="bo", basefmt="b-")
        axes[0, 0].axhline(umbral_leverage, color='orange', linestyle='--', label=f'Umbral ({umbral_leverage:.2f})')
        axes[0, 0].set_title("1. Apalancamiento (Leverage h_ii)")
        axes[0, 0].set_xlabel("Índice de Muestra")
        axes[0, 0].legend()
        axes[0, 0].grid(True, linestyle=':', alpha=0.6)
        # 2. Distancia de Cook
        axes[0, 1].stem(range(n), cooks_d, markerfmt="ro", basefmt="r-")
        axes[0, 1].axhline(umbral_cook, color='red', linestyle='--', label=f'Umbral Crítico ({umbral_cook:.3f})')
        axes[0, 1].set_title("2. Distancia de Cook (D_i)")
        axes[0, 1].set_xlabel("Índice de Muestra")
        axes[0, 1].legend()
        axes[0, 1].grid(True, linestyle=':', alpha=0.6)
        # 3. DFFITS
        axes[1, 0].stem(range(n), dffits, markerfmt="go", basefmt="g-")
        axes[1, 0].axhline(umbral_dffits, color='purple', linestyle='--', label=f'+ Umbral ({umbral_dffits:.2f})')
        axes[1, 0].axhline(-umbral_dffits, color='purple', linestyle='--', label=f'- Umbral (-{umbral_dffits:.2f})')
        axes[1, 0].set_title("3. DFFITS (Impacto en Predicción y_hat)")
        axes[1, 0].set_xlabel("Índice de Muestra")
        axes[1, 0].legend()
        axes[1, 0].grid(True, linestyle=':', alpha=0.6)
        # 4. DFBETAS
        axes[1, 1].stem(range(n), dfbetas[:, 1], markerfmt="mo", basefmt="m-")
        axes[1, 1].axhline(umbral_dfbetas, color='brown', linestyle='--', label=f'+ Umbral ({umbral_dfbetas:.2f})')
        axes[1, 1].axhline(-umbral_dfbetas, color='brown', linestyle='--', label=f'- Umbral (-{umbral_dfbetas:.2f})')
        axes[1, 1].set_title("4. DFBETAS (Impacto en Pendiente w)")
        axes[1, 1].set_xlabel("Índice de Muestra")
        axes[1, 1].legend()
        axes[1, 1].grid(True, linestyle=':', alpha=0.6)
        # Ajuste de layout seguro
        fig.tight_layout()
        st.pyplot(fig)
        st.write("---")
        # Interfaz de Diagnóstico y Evaluación
        st.subheader("🕵️‍‏♂️ Evaluación del Diagnóstico Auditor")
        indices_sospechosos = st.multiselect(
            "Selecciona los números de índice que identificas como saboteadores:",
            options=list(range(n))
        )
        revelar = st.button("🔍 Validar Diagnóstico y Analizar Métricas")
        if revelar:
            real_saboteadores = set(df_auditoria[df_auditoria['Tipo'] == 'Saboteador'].index)
            seleccionados = set(indices_sospechosos)
            df_metricas_todas = pd.DataFrame({
                'Index': df_auditoria.index,
                'Tipo Real': df_auditoria['Tipo'],
                'X': df_auditoria['X'].round(2),
                'Y': df_auditoria['Y'].round(2),
                'Leverage (hii)': np.round(leverage, 3),
                'Residuo Stud': np.round(stud_residuals, 3),
                'Cook D': np.round(cooks_d, 3),
                'DFFITS': np.round(dffits, 3),
                'DFBETA (w)': np.round(dfbetas[:, 1], 3)
            }).set_index('Index')
            if seleccionados == real_saboteadores:
                st.balloons()
                st.success(f"🎉 ¡DIAGNÓSTICO PERFECTO! Identificaste exactamente los puntos saboteadores: {list(real_saboteadores)}")
                st.write("### Métricas de los Puntos Saboteadores")
                st.dataframe(df_metricas_todas.loc[list(real_saboteadores)])
            else:
                st.error("⚠️ El diagnóstico fue incorrecto o incompleto. Revisa el análisis detallado a continuación:")
                falsos_positivos = list(seleccionados - real_saboteadores)
                falsos_negativos = list(real_saboteadores - seleccionados)
                if falsos_positivos:
                    st.warning(f"❌ **Falsos Positivos ({len(falsos_positivos)}):** Marcaste los puntos {falsos_positivos}, pero eran datos BASE normales.")
                    st.write("#### ¿Por qué te confundieron estos puntos base?")
                    st.dataframe(df_metricas_todas.loc[falsos_positivos])
                if falsos_negativos:
                    st.error(f"🙈 **Falsos Negativos ({len(falsos_negativos)}):** Se te escaparon los puntos saboteadores reales en los índices {falsos_negativos}.")
                    st.write("#### Métricas de los Saboteadores que pasaron desapercibidos:")
                    st.dataframe(df_metricas_todas.loc[falsos_negativos])
                aciertos = list(seleccionados.intersection(real_saboteadores))
                if aciertos:
                    st.info(f"✅ **Aciertos Parciales:** Identificaste correctamente los saboteadores en los índices {aciertos}.")
        st.write("---")
        st.write("---")
        # ---------------------------------------------------------------------
        # DESAFÍO ADICIONAL: PREDECIR LA UBICACIÓN ESPACIAL (X, Y)
        # ---------------------------------------------------------------------
        st.subheader("🎯 Desafío Geo-Métrico: Predice las Coordenadas (X, Y) del Saboteador")
        st.markdown("""
        **Reglas del Desafío:**
        A partir de los signos y valores de **Leverage (h_ii)**, **Residuo (r_i)** y **DFBETAS**, predice dónde está ubicado el punto en el plano X, Y:
        - **h_ii alto** -> X extremo (muy lejos de la línea vertical del promedio de X).
        - **r_i > 0** -> Por encima de la recta de regresión.
        - **r_i < 0** -> Por debajo de la recta de regresión.
        """)
        col_pred_1, col_pred_2 = st.columns([1, 1.2])
        with col_pred_1:
            idx_a_predecir = st.selectbox("Selecciona el índice que quieres estimar:", options=list(range(n)))
            x_promedio = float(np.mean(df_auditoria['X']))
            y_promedio = float(np.mean(df_auditoria['Y']))
            pred_x = st.number_input(f"Estimación de X para el índice {idx_a_predecir}:", value=float(round(x_promedio, 2)))
            pred_y = st.number_input(f"Estimación de Y para el índice {idx_a_predecir}:", value=float(round(y_promedio, 2)))
            lev_p = float(leverage[idx_a_predecir])
            res_p = float(stud_residuals[idx_a_predecir])
            pinta_x = "Extremo (Muy a la izquierda o derecha)" if lev_p > umbral_leverage else "Cercano al centro de la población (X promedio)"
            pinta_y = "Por ARRIBA de la línea de tendencia" if res_p > 0 else "Por DEBAJO de la línea de tendencia"
            st.info(f"💡 **Pistas Diagnósticas para el índice {idx_a_predecir}:**\n" +
                    f"- Posición en X: **{pinta_x}** (h_ii = {lev_p:.3f})\n" +
                    f"- Posición en Y: **{pinta_y}** (r_i = {res_p:.2f})")
            evaluar_click = st.button("📏 Evaluar Estimación Espacial")

        with col_pred_2:
            # Graficar la recta de regresión y la posición estimada del estudiante
            fig_gui, ax_gui = plt.subplots(figsize=(7, 4.5))
            x_vals = np.linspace(df_auditoria['X'].min() - 5, df_auditoria['X'].max() + 5, 100)
            y_vals = model_aud.params['const'] + model_aud.params['X'] * x_vals
            # 1. Dibujar la línea de tendencia del modelo
            ax_gui.plot(x_vals, y_vals, color='red', linewidth=2, label='Línea del Modelo (Regresión)')
            # 2. Dibujar la línea vertical del promedio de X
            ax_gui.axvline(x_promedio, color='gray', linestyle=':', label=f'Promedio de X ({x_promedio:.1f})')
            # 3. Dibujar la predicción hecha por el estudiante
            ax_gui.scatter(pred_x, pred_y, color='orange', s=150, marker='*', label=f'Tu Estimación ({pred_x:.1f}, {pred_y:.1f})', zorder=5)
            # 4. Si presiona evaluar, revelar la posición real del punto
            if evaluar_click:
                real_x = float(df_auditoria.loc[idx_a_predecir, 'X'])
                real_y = float(df_auditoria.loc[idx_a_predecir, 'Y'])
                ax_gui.scatter(real_x, real_y, color='green', s=120, marker='o', label=f'Punto Real ({real_x:.1f}, {real_y:.1f})', zorder=6)
                ax_gui.plot([pred_x, real_x], [pred_y, real_y], color='black', linestyle='--', alpha=0.7, label='Error de Distancia')
            ax_gui.set_xlim(df_auditoria['X'].min() - 10, df_auditoria['X'].max() + 10)
            ax_gui.set_ylim(df_auditoria['Y'].min() - 20, df_auditoria['Y'].max() + 30)
            ax_gui.set_xlabel("Variable X")
            ax_gui.set_ylabel("Variable Y")
            ax_gui.set_title("Marco Referencial del Modelo (Sin Puntos)")
            ax_gui.legend(loc='upper left', fontsize=8)
            ax_gui.grid(True, linestyle=':', alpha=0.6)
            fig_gui.tight_layout()
            st.pyplot(fig_gui)
            # Retroalimentación numérica tras presionar el botón
            if evaluar_click:
                real_x = float(df_auditoria.loc[idx_a_predecir, 'X'])
                real_y = float(df_auditoria.loc[idx_a_predecir, 'Y'])
                dist_error = np.sqrt((pred_x - real_x)**2 + (pred_y - real_y)**2)
                if dist_error < 10.0:
                    st.success(f"🎯 ¡Excelente intuición espacial! Error de distancia: `{dist_error:.2f}` unidades.")
                else:
                    st.warning(f"📐 Buena aproximación. Error de distancia: `{dist_error:.2f}` unidades.")